---
title: "Introduction" 
---

 
---

### Rooting for the home team: An analysis of reffing bias for home teams in the NFL 
The term “home field advantage” - the widely accepted idea that it is considered better for a team to play on its own field or in its own stadium that in that of the opponent - is often thrown around in the world of sports. This idea certainly persists in the National Football League (NFL). For example, securing home field advantage for the playoffs is the goal for most teams during the regular season, as it is likely to improve their odds of winning. In fact - only one first seed team has ever been the “underdog” (in Vegas odds) when playing at home in the playoffs. So what is it about playing that home that increases a teams chances of winning? While some factors may include the support of home fans and familiarity with the facility, another purported reason is the leniency of referees on the home team. It has often been suggested by fans and players that the home team receives less calls that the opponent. However, the accuracy of these accucastions has not been tested.
 This study investigates whether there is significant bias in the number of penalties accepted for home and away teams, and whether the number of penalties impacts the likelihood of the home team winning. I am predicting that there will be a general effect for home field advantage and that the number of penalties is a significant predictor of the outcome of the game. The former prediction would identify the presence of a home field bias, whereas the latter would identify if the number of penalties impacts game outcome. Since there are different yards associated with different penalties, I will also be testing if there is a correlation in penalty yards between home and away teams to ensure that any results are not driven by a difference in penalty types for each group.  
---

H1~0~: There is no difference in the number of penalties called between home and away teams

H1~1~: Home teams receive significantly less penalties compared to away teams

---	
	
H2~0~: There is no correlation between penalty yards and number of penalties

H2~1~: There is a significant correlation between penalty yards and the number of penalties

---

H3~0~: The difference in number of penalties between home and away teams has no relationship to whether the home team wins

H3~1~: The difference in the number of penalties between home and away teams is a significant predictor of the home team winning

---  

 

